CREATE TABLE IF NOT EXISTS sys_department (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  name VARCHAR(64) NOT NULL COMMENT '部门名称',
  parent_id BIGINT DEFAULT 0 COMMENT '父部门ID',
  leader VARCHAR(64) COMMENT '负责人',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
  sort INT NOT NULL DEFAULT 0 COMMENT '排序'
) COMMENT='部门表';

CREATE TABLE IF NOT EXISTS sys_dict (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  type VARCHAR(64) NOT NULL COMMENT '字典类型',
  name VARCHAR(64) NOT NULL COMMENT '显示名称',
  code VARCHAR(64) NOT NULL COMMENT '存储值',
  sort INT NOT NULL DEFAULT 0 COMMENT '排序'
) COMMENT='字典表';

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  name VARCHAR(64) NOT NULL COMMENT '姓名',
  phone VARCHAR(32) COMMENT '手机号',
  email VARCHAR(128) COMMENT '邮箱',
  gender CHAR(1) COMMENT '性别',
  dept_id BIGINT COMMENT '部门ID',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  CONSTRAINT fk_user_dept FOREIGN KEY (dept_id) REFERENCES sys_department(id)
) COMMENT='用户表';
